CREATE TABLE IF NOT EXISTS vit_schedule (
    ID INT NOT NULL AUTO_INCREMENT,
    DAY_OF_WEEK INT NOT NULL,
    IS_WORKING CHAR(1) NOT NULL DEFAULT 'N',
    TIME_FROM VARCHAR(5) DEFAULT NULL,
    TIME_TO VARCHAR(5) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY ux_day (DAY_OF_WEEK)
);

INSERT INTO vit_schedule (DAY_OF_WEEK, IS_WORKING, TIME_FROM, TIME_TO) VALUES
(1, 'Y', '09:00', '18:00'),
(2, 'Y', '09:00', '18:00'),
(3, 'Y', '09:00', '18:00'),
(4, 'Y', '09:00', '18:00'),
(5, 'Y', '09:00', '18:00'),
(6, 'N', NULL, NULL),
(7, 'N', NULL, NULL);
